# Manually triggers a workflow that builds a Docker image and publishes it to Docker Hub.

name: Manually Publish Docker Image

on: workflow_dispatch

jobs:
  variables:
    name: Gather Variables
    runs-on: ubuntu-20.04
    outputs:
      version: ${{steps.version.outputs.SQUIDWARDBOT_VERSION}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get Version
        id: version
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: './gradle.properties'
          properties: 'SQUIDWARDBOT_VERSION'

      - name: Print Semantic Versioning
        run: echo ${{steps.version.outputs.SQUIDWARDBOT_VERSION}}
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow
  jar:
    name: Build JAR
    runs-on: ubuntu-20.04
    needs: [variables]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Grant Execute Permissions for Gradlew
        run: chmod 777 gradlew

      - name: Build Jar with Gradle
        run: ./gradlew fatJar

      - name: Output Directory Structure
        run: ls -Rla

      - name: Add Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SquidwardBot-${{needs.variables.outputs.version}}
          path: ./build/libs/SquidwardBot.jar
  release-gh:
    name: Create Github Release
    runs-on: ubuntu-20.04
    needs: [variables, changelog, jar]
    steps:
      - name: Download SquidwardBot JAR
        uses: actions/download-artifact@v2
        with:
          name: SquidwardBot
          path: build/libs
      - name: Create Github Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{needs.variables.outputs.version}}
          title: Version ${{needs.variables.outputs.version}}
          files: |
            ./build/libs/SquidwardBot.jar
  docker-publish:
    name: Builds and Publishes Docker Image
    runs-on: ubuntu-20.04
    needs: [variables, changelog, jar]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Gather Docker Metadata
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          images: theblacksquidward/squidwardbot
          tags: type=semver,pattern={{version}},value=v${{needs.variables.outputs.version}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
